edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true

# Unstable features (require nightly Rust)
# Commented out for stable compatibility
# format_strings = false
# format_macro_matchers = true
# format_macro_bodies = true
